import { Card, CardType, GemType, ItemType } from './card';

export const CARDS: Card[][] = [[
	{
		id: 0,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 00',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'A Fine Hat',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 1,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 01',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Leather Gloves',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 2,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 02',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Pocket Calculator',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 1 },
		leftGem: GemType.none,
		rightGem: 0
	}
	], [
	{
		id: 100,
		level: 1,
		cardType: CardType.event,
		cardName: 'Cave-In',
		cardImg: '',
		cardText: 'Remove a tile',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: null,
		rightGem: null
	},
	{
		id: 101,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Musk Deer',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 1, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Fangs',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 1 },
		leftGem: GemType.Brawn,
		rightGem: 0
	},
	{
		id: 102,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Water-Filled Pit',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Clear Lens',
		itemImg: '',
		itemText: 'Shuffle a trap back into its deck and draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.vsEnemies,
		rightGem: -1
	}
	], [
	{
		id: 201,
		level: 2,
		cardType: CardType.enemy,
		cardName: 'Agogwe',
		cardImg: '',
		cardText: 'Legendary African Ape',
		cardStats: { Brains: 4, Brawn: 4, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 2
	},
	{
		id: 202,
		level: 2,
		cardType: CardType.trap,
		cardName: 'Giant Spider Web',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: 5 },
		itemType: ItemType.permanent,
		itemName: 'Silk Armor',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 2
	},
	{
		id: 203,
		level: 2,
		cardType: CardType.event,
		cardName: 'Surge of Power',
		cardImg: '',
		cardText: 'Roll a die<ul><li>1–2: gain a wound</li><li>5–6: heal a wound</li></ul>',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: null,
		rightGem: null
	}
	], [
	{
		id: 301,
		level: 2,
		cardType: CardType.trap,
		cardName: 'Distorted Gravity',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 8, Brawn: null, Bravado: null },
		itemType: ItemType.useNow,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Remove a tile<br>Draw a tile',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: GemType.Brawn * GemType.Bravado,
		rightGem: 2
	},
	{
		id: 302,
		level: 2,
		cardType: CardType.event,
		cardName: 'Earthquake',
		cardImg: '',
		cardText: '−1 to your next die roll',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: null,
		rightGem: null
	},
	{
		id: 303,
		level: 2,
		cardType: CardType.enemy,
		cardName: 'Surma',
		cardImg: '',
		cardText: 'Finnish Devil-dog',
		cardStats: { Brains: 6, Brawn: 6, Bravado: 6 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains * GemType.Brawn * GemType.Bravado,
		rightGem: 1
	}
]];
