import {Card, CardType, GemType, ItemType} from './card';

export const CARDS: Card[][] = [[
	{
		id: 0,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 00',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'A Fine Hat',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 1,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 01',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Leather Gloves',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 2,
		level: 0,
		cardType: CardType.starter,
		cardName: 'Starter 02',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Pocket Calculator',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 1 },
		leftGem: GemType.none,
		rightGem: 0
	}
	], [
	{
		id: 1000,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Anaconda',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Regurgitated Meal',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1001,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Angry Gibbon',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 5, Brawn: 1, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Crude Spear',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1002,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Baboon',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 4, Brawn: 2, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Stone Knife',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1003,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Badger',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 3, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1004,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Bats',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 1, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Fast Food',
		itemImg: '',
		itemText: 'Heal one wound',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1005,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Boar',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Bacon!',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 2, Brawn: 0, Bravado: 0 },
		leftGem: GemType.enBravado,
		rightGem: 1
	},
	{
		id: 1006,
		level: 1,
		cardType: CardType.event,
		cardName: 'Brief Reprieve',
		cardImg: '',
		cardText: 'Heal a wound',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: null,
		leftGem: null,
		rightGem: null
	},
	{
		id: 1007,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Carefully Laid Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Cheese!',
		itemImg: '',
		itemText: 'Heal one wound',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 1008,
		level: 1,
		cardType: CardType.event,
		cardName: 'Cave-In',
		cardImg: '',
		cardText: 'Remove a tile',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: null,
		leftGem: null,
		rightGem: null
	},
	{
		id: 1009,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Cave Octopus',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 4, Brawn: 1, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'A Very Fancy Hat',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1010,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Centipedes',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 5 },
		itemType: ItemType.useOnce,
		itemName: 'That creepy crawly feeling all over…',
		itemImg: '',
		itemText: 'Draw an extra tile, then discard one',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1011,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Chickcharney',
		cardImg: '',
		cardText: 'Owl monster of the Bahamas',
		cardStats: { Brains: 4, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Magic Feather',
		itemImg: '',
		itemText: 'Move one extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1012,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Coconut Crab',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 3, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.enBrawn,
		rightGem: 1
	},
	{
		id: 1013,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Collapsing Wall',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: null, Bravado: 3 },
		itemType: ItemType.useNext,
		itemName: 'Open Passage',
		itemImg: '',
		itemText: 'Move to any adjacent tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1014,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Cougar',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.vsTraps,
		rightGem: 2
	},
	{
		id: 1015,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Crocodile',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 5, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Tough Hide',
		itemImg: '',
		itemText: 'Discard an enemy before you roll',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1016,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Cunning Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Carrots!',
		itemImg: '',
		itemText: 'Heal one wound',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 0
	},
	{
		id: 1017,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Dart Frog',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 4, Brawn: 1, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Poison Dart',
		itemImg: '',
		itemText: 'Reduce an Enemy’s Brawn by 3',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1018,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Dart Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: null, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Spring Mechanism',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1019,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Debris Pile',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Runestone',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1020,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Dense Smoke',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Guttering Torch',
		itemImg: '',
		itemText: 'Draw an extra tile, then discard one',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1021,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Drop Bear',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 3, Bravado: 1 },
		itemType: ItemType.useNext,
		itemName: 'Where did that come from?',
		itemImg: '',
		itemText: 'Move to any adjacent tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1022,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Falling Rocks',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 2, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Big, pointy rock',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1023,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Falling Sand',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: null, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Fulgurite',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 2, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1024,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Fire Ants',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 4 },
		itemType: ItemType.permanent,
		itemName: 'A great source of protein',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 2, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1025,
		level: 1,
		cardType: CardType.event,
		cardName: 'Flash Flood',
		cardImg: '',
		cardText: 'The player on your right moves your character one space',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: null,
		leftGem: null,
		rightGem: null
	},
	{
		id: 1026,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Gnomes',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 1, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Alchemical Elixir',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1027,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Hibernating Grizzly',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 5, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Bear Pelt',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1028,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Hyenas',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 3, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.vsEnemies,
		rightGem: 2
	},
	{
		id: 1029,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Imp',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 4, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Brimstone',
		itemImg: '',
		itemText: 'Shuffle a trap back into its deck<br>Draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1030,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Jackalope',
		cardImg: '',
		cardText: 'Ferocious antlered rabbit of North America',
		cardStats: { Brains: 3, Brawn: 2, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Antlers',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1031,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Kangaroo',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 3, Bravado: 1 },
		itemType: ItemType.useNext,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Move an extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1032,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'King Cobra',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 4 },
		itemType: ItemType.permanent,
		itemName: 'Cobra Fangs',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1033,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Komodo Dragon',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 4, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Scale Armor',
		itemImg: '',
		itemText: 'Force an enemy to reroll a die',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1034,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Koolakamba',
		cardImg: '',
		cardText: 'Legendary African ape',
		cardStats: { Brains: 1, Brawn: 4, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Surprisingly detailed schematics',
		itemImg: '',
		itemText: '+3 vs one trap',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1035,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Kumi Lizard',
		cardImg: '',
		cardText: 'Giant tree lizard of New Zealand',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 4 },
		itemType: ItemType.useOnce,
		itemName: 'Forked Tongue',
		itemImg: '',
		itemText: 'Reduce an Enemy’s Bravado by 3',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1036,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Lightning Sand',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 2, Bravado: null },
		itemType: ItemType.useOnce,
		itemName: 'Sand in your shoes',
		itemImg: '',
		itemText: 'Move one extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1037,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Menehune',
		cardImg: '',
		cardText: 'Tiny builders and tricksters of Hawaii',
		cardStats: { Brains: 5, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Enchanted Hammer',
		itemImg: '',
		itemText: 'Discard a trap before you roll',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1038,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Moles',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: 2 },
		itemType: ItemType.useNext,
		itemName: 'A convenient hole',
		itemImg: '',
		itemText: 'Move to any adjacent tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 1
	},
	{
		id: 1039,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Mongoose',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 2, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.enBrains,
		rightGem: 1
	},
	{
		id: 1040,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Mothman',
		cardImg: '',
		cardText: 'Bird-man of West Virginia',
		cardStats: { Brains: 2, Brawn: 4, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Tattered Wings',
		itemImg: '',
		itemText: 'Move an extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1041,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Mountain Fennec',
		cardImg: '',
		cardText: 'Legendary fox of the Sahara',
		cardStats: { Brains: 2, Brawn: 3, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Foxtail',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1042,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Mountain Goat',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 3, Bravado: 1 },
		itemType: ItemType.useNext,
		itemName: 'Impossible Passage',
		itemImg: '',
		itemText: 'Move to any adjacent tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1043,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Musk Deer',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 1, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Fangs',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 1 },
		leftGem: GemType.Brawn,
		rightGem: 0
	},
	{
		id: 1044,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Onza',
		cardImg: '',
		cardText: 'Legendary South American jaguar',
		cardStats: { Brains: 1, Brawn: 3, Bravado: 3 },
		itemType: ItemType.useNext,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Move an extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1045,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Oubliette',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'Discarded Rope',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1046,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Panther',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 3, Bravado: 3 },
		itemType: ItemType.useOnce,
		itemName: 'Black Fur',
		itemImg: '',
		itemText: 'Shuffle an enemy back into its pile<br>Draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: -1
	},
	{
		id: 1047,
		level: 1,
		cardType: CardType.event,
		cardName: 'The path grows clearer',
		cardImg: '',
		cardText: 'Add a tile',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: null,
		leftGem: null,
		rightGem: null
	},
	{
		id: 1048,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Pit Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: 2, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Bullwhip',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1049,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Puma',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 2, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn * GemType.Bravado,
		rightGem: -2
	},
	{
		id: 1050,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Python',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1051,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Rattlesnake',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 4 },
		itemType: ItemType.useOnce,
		itemName: 'Rattle',
		itemImg: '',
		itemText: 'Reduce an Enemy’s die roll by 2',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1052,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Rats',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 2, Bravado: 2 },
		itemType: ItemType.useNow,
		itemName: 'A less-than-satisfying meal',
		itemImg: '',
		itemText: 'Heal one wound',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 1
	},
	{
		id: 1053,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Razor Wire',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Cat o’ Nine Tails',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.none,
		rightGem: 1
	},
	{
		id: 1054,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Recluse Spider',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 3 },
		itemType: ItemType.useNow,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Add a tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1055,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Rolling Boulder',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: 3, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Memory of your truly epic escape',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1056,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Scattered Pebbles',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Small glowing stone',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 1, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 0
	},
	{
		id: 1057,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Scorpions',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 3 },
		itemType: ItemType.useOnce,
		itemName: 'Anti-Venom',
		itemImg: '',
		itemText: 'Heal one wound',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1058,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Skunk',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 4 },
		itemType: ItemType.useOnce,
		itemName: 'Scent Gland',
		itemImg: '',
		itemText: 'Shuffle an enemy back into its deck<br>Draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1059,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Slab of Rock',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 2, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Lots of dust and rubble',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1060,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Spear Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: null, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Silvered Spear Tip',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1061,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Spike Trap',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: 2, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Dismantled Trigger',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 1 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1062,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Squirrels',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 2, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Pointy Stick',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 1, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1063,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Tasmanian Devil',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 4, Brawn: 2, Bravado: 1 },
		itemType: ItemType.useNow,
		itemName: 'Centripetal Force',
		itemImg: '',
		itemText: 'Rotate one tile',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1064,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Tiger',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 4, Bravado: 2 },
		itemType: ItemType.permanent,
		itemName: 'Tiger Claw',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1065,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Tripwire Maze',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 1, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Lariat',
		itemImg: '',
		itemText: 'Shuffle an enemy back into its deck<br>Draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.vsTraps,
		rightGem: -1
	},
	{
		id: 1066,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Wandering Spider',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 3, Brawn: 1, Bravado: 3 },
		itemType: ItemType.permanent,
		itemName: 'Crunch',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 2 },
		leftGem: GemType.Brawn,
		rightGem: 1
	},
	{
		id: 1067,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Wasps',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 4 },
		itemType: ItemType.useOnce,
		itemName: 'Teeny Tiny Wings',
		itemImg: '',
		itemText: 'Draw an extra tile, then put one back',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1068,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Water-filled Pit',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Clear Lens',
		itemImg: '',
		itemText: 'Shuffle a trap back into its deck<br>Draw a new card',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.vsEnemies,
		rightGem: -1
	},
	{
		id: 1069,
		level: 1,
		cardType: CardType.trap,
		cardName: 'Whirling Blades',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: 3, Bravado: 2 },
		itemType: ItemType.useOnce,
		itemName: 'Glittering Sickle',
		itemImg: '',
		itemText: 'Draw an extra card, then discard one',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1070,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Wolf',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 2, Brawn: 4, Bravado: 1 },
		itemType: ItemType.permanent,
		itemName: 'Learn to Howl',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 2, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1071,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Wolpertinger',
		cardImg: '',
		cardText: 'German chimera',
		cardStats: { Brains: 1, Brawn: 3, Bravado: 2 },
		itemType: ItemType.useNext,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Move an extra space',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 1
	},
	{
		id: 1072,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Young Bear',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 4, Bravado: 1 },
		itemType: ItemType.useOnce,
		itemName: 'Bear Claw',
		itemImg: '',
		itemText: '+3 vs one Enemy',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 1
	},
	{
		id: 1073,
		level: 1,
		cardType: CardType.enemy,
		cardName: 'Zombie',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 1, Brawn: 1, Bravado: 5 },
		itemType: ItemType.permanent,
		itemName: 'Rags',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 2, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brawn,
		rightGem: 1
	}
	], [
	{
		id: 201,
		level: 2,
		cardType: CardType.enemy,
		cardName: 'Agogwe',
		cardImg: '',
		cardText: 'Legendary<br>African Ape',
		cardStats: { Brains: 4, Brawn: 4, Bravado: null },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Bravado,
		rightGem: 2
	},
	{
		id: 202,
		level: 2,
		cardType: CardType.trap,
		cardName: 'Giant Spider Web',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: null, Brawn: null, Bravado: 5 },
		itemType: ItemType.permanent,
		itemName: 'Silk Armor',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 2, Bravado: 0 },
		leftGem: GemType.Brains,
		rightGem: 2
	},
	{
		id: 203,
		level: 2,
		cardType: CardType.event,
		cardName: 'Surge of Power',
		cardImg: '',
		cardText: 'Roll a die<ul><li>1–2: gain a wound</li><li>5–6: heal a wound</li></ul>',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: null,
		rightGem: null
	}
	], [
	{
		id: 301,
		level: 2,
		cardType: CardType.trap,
		cardName: 'Distorted Gravity',
		cardImg: '',
		cardText: '',
		cardStats: { Brains: 8, Brawn: null, Bravado: null },
		itemType: ItemType.useNow,
		itemName: 'TBD',
		itemImg: '',
		itemText: 'Remove a tile<br>Draw a tile',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: GemType.Brawn * GemType.Bravado,
		rightGem: 2
	},
	{
		id: 302,
		level: 2,
		cardType: CardType.event,
		cardName: 'Earthquake',
		cardImg: '',
		cardText: '−1 to your next die roll',
		cardStats: { Brains: null, Brawn: null, Bravado: null },
		itemType: ItemType.none,
		itemName: '',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: null, Brawn: null, Bravado: null },
		leftGem: null,
		rightGem: null
	},
	{
		id: 303,
		level: 2,
		cardType: CardType.enemy,
		cardName: 'Surma',
		cardImg: '',
		cardText: 'Finnish<br>Devil-dog',
		cardStats: { Brains: 6, Brawn: 6, Bravado: 6 },
		itemType: ItemType.permanent,
		itemName: 'TBD',
		itemImg: '',
		itemText: '',
		itemStats: { Brains: 0, Brawn: 0, Bravado: 0 },
		leftGem: GemType.Brains * GemType.Brawn * GemType.Bravado,
		rightGem: 1
	}
]];
