import { Player } from './player';

export const CHARACTERS: Player[] = [
	{
		id: 0,
		name: 'Eva Rast',
		shortName: 'Eva',
		description: '',
		playerPower: 0,
		powerName: '',
		powerDescription: '',
		portrait: '',
		headshot: 'blank.gif',
		avatar: '',
		avatarStyle: { top: 0, left: 0 },
		stats: { Brains: 1, Brawn: 1, Bravado: 1 },
		displayStats: { Brains: '1', Brawn: '1', Bravado: '1' },
		location: 0,
		campLocation: 0,
		wounds: [],
		items: []
	},
	{
		id: 0,
		name: 'Kiki Manjaro',
		shortName: 'Kiki',
		description: '',
		playerPower: 0,
		powerName: '',
		powerDescription: '',
		portrait: '',
		headshot: 'blank.gif',
		avatar: '',
		avatarStyle: { top: 0, left: 0 },
		stats: { Brains: 1, Brawn: 1, Bravado: 1 },
		displayStats: { Brains: '1', Brawn: '1', Bravado: '1' },
		location: 0,
		campLocation: 0,
		wounds: [],
		items: []
	},
	{
		id: 0,
		name: 'Anna Purna',
		shortName: 'Anna',
		description: '',
		playerPower: 1,
		powerName: 'Robotics',
		powerDescription: 'A little mechanical companion to carry an extra item',
		portrait: '',
		headshot: 'blank.gif',
		avatar: '',
		avatarStyle: { top: 0, left: 0 },
		stats: { Brains: 1, Brawn: 1, Bravado: 1 },
		displayStats: { Brains: '1', Brawn: '1', Bravado: '1' },
		location: 0,
		campLocation: 0,
		wounds: [],
		items: []
	},
	{
		id: 0,
		name: 'Maddie Horn',
		shortName: 'Maddie',
		description: '',
		playerPower: 2,
		powerName: 'Vigorous',
		powerDescription: 'You may take an additional Wound before needing to go back and heal',
		portrait: '',
		headshot: 'blank.gif',
		avatar: '',
		avatarStyle: { top: 0, left: 0 },
		stats: { Brains: 1, Brawn: 1, Bravado: 1 },
		displayStats: { Brains: '1', Brawn: '1', Bravado: '1' },
		location: 0,
		campLocation: 0,
		wounds: [],
		items: []
	}
];
